version: '3'

services:
  patroni-metrics:
    build: .
    restart: always
    ports:
      - "5077:5077"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5077/health"]
      interval: 30s
      timeout: 10s
      retries: 3
